name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'

      - name: Set up Java
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install cython
          pip install python-for-android
          pip install buildozer
          pip install kivy

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3 \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libltdl-dev \
            libffi-dev \
            libssl-dev \
            autoconf \
            automake \
            libtool \
            pkg-config

      - name: Set up Android SDK
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip
          mkdir -p ${GITHUB_WORKSPACE}/android-sdk/cmdline-tools
          mv cmdline-tools ${GITHUB_WORKSPACE}/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=${GITHUB_WORKSPACE}/android-sdk" >> $GITHUB_ENV
          echo "PATH=${GITHUB_WORKSPACE}/android-sdk/cmdline-tools/latest/bin:${GITHUB_WORKSPACE}/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Download and setup Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          mv android-ndk-r25b ${GITHUB_WORKSPACE}/android-ndk
          echo "ANDROID_NDK_HOME=${GITHUB_WORKSPACE}/android-ndk" >> $GITHUB_ENV
          echo "PATH=${ANDROID_NDK_HOME}:$PATH" >> $GITHUB_ENV

      - name: Create debug keystore
        run: |
          keytool -genkeypair -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

      - name: Set environment variables
        run: |
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=${GITHUB_WORKSPACE}/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=${GITHUB_WORKSPACE}/android-ndk" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=${GITHUB_WORKSPACE}/android-ndk" >> $GITHUB_ENV
          echo "ANDROID_SDK_HOME=${GITHUB_WORKSPACE}/android-sdk" >> $GITHUB_ENV

      - name: Setup python-for-android
        run: |
          mkdir -p .buildozer/android/platform
          git clone https://github.com/kivy/python-for-android.git .buildozer/android/platform/python-for-android
          cd .buildozer/android/platform/python-for-android
          python setup.py install

      - name: Build APK
        env:
          BUILDOZER_WARN_ON_ROOT: 0
        run: |
          export PATH=$PATH:${GITHUB_WORKSPACE}/android-sdk/platform-tools
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: APK
          path: bin/*.apk

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: buildozer_logs
          path: |
            .buildozer/android/build/*.log
            .buildozer/android/platform/*/build/*.log
