name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Required Packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential automake autoconf libtool m4 python3-pip
          pip install --upgrade pip setuptools wheel

      - name: Install Buildozer and Dependencies
        run: |
          pip install cython
          pip install buildozer
          pip install git+https://github.com/kivy/python-for-android.git

      - name: Initialize Buildozer
        run: |
          buildozer init

      - name: Fix LibFFI Autogen Issues
        run: |
          # Replace obsolete macros in libffi's configure.ac before running autoreconf
          sed -i 's/AC_CANONICAL_SYSTEM/AC_CANONICAL_HOST/' path/to/libffi/configure.ac
          sed -i 's/AC_PROG_LIBTOOL/LT_INIT/' path/to/libffi/configure.ac
          autoreconf --force --install

      - name: Build APK
        run: |
          buildozer android debug
