name: Build APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'
      
      - name: Set up Java
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0
          pip install cython==0.29.33
          pip install kivy==2.3.0
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0-dev \
            gstreamer1.0-plugins-{bad,base,good,ugly} \
            gstreamer1.0-{tools,x} \
            libffi-dev \
            libssl-dev \
            autoconf \
            automake \
            libtool \
            pkg-config
      
      - name: Set up buildozer.spec
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          sed -i 's/^android.ndk =.*/android.ndk = 25b/' buildozer.spec
          sed -i 's/^android.ndk_path =.*/android.ndk_path = /home/runner/.buildozer/android/platform/android-ndk-r25b/' buildozer.spec
          sed -i 's/^android.sdk =.*/android.sdk = 33/' buildozer.spec
          sed -i 's/^p4a.branch =.*/p4a.branch = master/' buildozer.spec
      
      - name: Create missing directories
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          
      - name: Download and extract Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip -d $HOME/.buildozer/android/platform/
          rm android-ndk-r25b-linux.zip
      
      - name: Set environment variables
        run: |
          echo "ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROID_NDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "PATH=$HOME/.buildozer/android/platform/android-ndk-r25b:$PATH" >> $GITHUB_ENV
      
      - name: Build APK
        run: |
          export PATH=$ANDROID_NDK_HOME:$PATH
          export CFLAGS="-I$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include"
          buildozer android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 0
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: bin/*.apk
      
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: buildozer_logs
          path: .buildozer/android/buildozer.log
