name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            python3-pip \
            python3-dev \
            libffi-dev \
            libssl-dev \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            autoconf \
            automake \
            libtool \
            pkg-config

      - name: Install buildozer
        run: |
          pip install --upgrade pip
          pip install --upgrade Cython==0.29.33
          pip install buildozer==1.5.0

      - name: Initialize buildozer
        run: |
          buildozer init
          # Modify buildozer.spec if needed
          sed -i 's/^android.sdk = .*/android.sdk = 33/g' buildozer.spec
          sed -i 's/^android.ndk = .*/android.ndk = 25c/g' buildozer.spec
          sed -i 's/^android.api = .*/android.api = 33/g' buildozer.spec

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Terminal
          path: bin/*.apk

      - name: Upload build logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: buildozer_logs
          path: .buildozer/android/build/*.log
