name: Build Android App with Kivy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          libffi-dev \
          libssl-dev \
          python3-dev \
          python3-pip \
          libtool \
          autoconf \
          automake \
          cmake \
          unzip \
          wget \
          curl \
          libncurses5 \
          libncurses5-dev \
          zlib1g-dev \
          liblzma-dev \
          pkg-config \
          python3-setuptools \
          libreadline-dev

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/Android/Sdk
        echo "y" | sdkmanager --install "platform-tools" "platforms;android-21" "build-tools;30.0.3" "ndk;21.3.6528147" "system-images;android-21;default;armeabi-v7a"
        echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_HOME=$HOME/Android/Sdk/ndk/21.3.6528147" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/Android/Sdk/tools:$HOME/Android/Sdk/tools/bin:$HOME/Android/Sdk/platform-tools" >> $GITHUB_ENV

    - name: Install Buildozer
      run: |
        pip install buildozer

    - name: Run Buildozer to build Android app
      run: |
        cd $GITHUB_WORKSPACE
        buildozer android debug

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: android-debug-apk
        path: ./bin/*.apk

    - name: Clean up
      run: |
        sudo apt-get autoremove -y
        sudo apt-get clean
