name: Build APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'
      - name: Set up Java
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Android Command Line Tools
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y wget unzip
          mkdir -p $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
      - name: Accept Android licenses
        run: |
          mkdir -p $HOME/android-sdk/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $HOME/android-sdk/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $HOME/android-sdk/licenses/android-sdk-preview-license
      - name: Install Android NDK
        run: |
          mkdir -p $HOME/android-sdk/ndk
          wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip -O ndk.zip
          unzip ndk.zip -d $HOME/android-sdk/ndk/
          echo "ANDROID_NDK_HOME=$HOME/android-sdk/ndk/android-ndk-r27c-linux" >> $GITHUB_ENV
          echo "PATH=$ANDROID_NDK_HOME:$PATH" >> $GITHUB_ENV
      - name: Install required Android SDK packages
        run: |
          yes | sdkmanager --install "platforms;android-30" "build-tools;30.0.3" "platform-tools" --sdk_root=${ANDROID_HOME}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install cython buildozer == 1.2.0
      - name: Install additional build dependencies
        run: |
          sudo apt-get install -y \
            libssl-dev \
            libffi-dev \
            build-essential \
            libsdl2-dev \
            libsdl2-image-dev \
            libltdl-dev \
            libtool \
            libsdl2-mixer-dev \
            gcc \
            g++ \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev
            sudo apt-get install software-properties-common
            sudo add-apt-repository ppa:jonathonf/gcc
            sudo apt-get install gcc-9
      - name: Build APK
        run: |
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: APK
          path: bin/*
      - name: Upload build logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: buildozer_logs
          path: .buildozer/android/build/*.log
