name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Buildozer dependencies
        uses: actions/cache@v3
        with:
          path: |
            .buildozer
            ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            python3-pip \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0 \
            gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good \
            autoconf \
            automake \
            libtool \
            pkg-config \
            wget \
            unzip \
            zip

      - name: Install buildozer and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade Cython==0.29.33
          pip install --upgrade buildozer==1.5.0
          pip install --upgrade virtualenv

      - name: Build APK
        run: |
          buildozer android clean
          buildozer -v android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 0

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Terminal
          path: bin/*.apk

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: buildozer_logs
          path: |
            .buildozer/android/build/*.log
            .buildozer/android/platform/build-arm64-v8a/build/*.log
