name: Build APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'
      
      - name: Set up Java
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        continue-on-error: true
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0
          pip install cython==0.29.33
          pip install kivy==2.3.0
      
      - name: Install system dependencies
        continue-on-error: true
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libgstreamer1.0-dev \
            gstreamer1.0-plugins-{bad,base,good,ugly} \
            gstreamer1.0-{tools,x} \
            libffi-dev \
            libssl-dev \
            autoconf \
            automake \
            libtool \
            pkg-config \
            autoconf-archive
      
      - name: Update autoconf
        run: |
          cd /tmp
          wget https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.gz
          tar xzf autoconf-2.71.tar.gz
          cd autoconf-2.71
          ./configure --prefix=/usr
          make
          sudo make install
      
      - name: Install libtool
        run: |
          cd /tmp
          wget https://ftp.gnu.org/gnu/libtool/libtool-2.4.7.tar.gz
          tar xzf libtool-2.4.7.tar.gz
          cd libtool-2.4.7
          ./configure --prefix=/usr
          make
          sudo make install
      
      - name: Build and install libffi
        run: |
          cd /tmp
          git clone https://github.com/libffi/libffi.git
          cd libffi
          ./autogen.sh
          autoreconf -fiv
          ./configure --prefix=/usr --disable-docs
          make
          sudo make install
      
      - name: Build APK
        continue-on-error: true
        run: |
          python -W ignore -m buildozer -v android debug || true
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: bin/*.apk
      
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: buildozer_logs
          path: ./*
