name: Build APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android Command Line Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          mkdir -p $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip
          unzip commandlinetools-linux-7302050_latest.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Accept Android licenses
        run: |
          mkdir -p $HOME/android-sdk/licenses
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > $HOME/android-sdk/licenses/android-sdk-license
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > $HOME/android-sdk/licenses/android-sdk-preview-license

      - name: Install required Android SDK packages
        run: |
          yes | sdkmanager --install "platforms;android-30" "build-tools;30.0.3" "platform-tools" --sdk_root=${ANDROID_HOME}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install cython buildozer

      - name: Install additional build dependencies
        run: |
          sudo apt-get install -y \
            libssl-dev \
            libffi-dev \
            build-essential \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            libtool \
            autoconf \
            automake \
            m4 \
            autoconf-archive
      - name: Create required files
        run: |
          touch AUTHORS ChangeLog NEWS README
          
      - name: Update configure.ac
        run: |
          echo 'AC_INIT([MyProject], [1.0])' > configure.ac
          echo 'AM_INIT_AUTOMAKE([-Wall -Werror foreign])' >> configure.ac
          echo 'AC_PROG_CC' >> configure.ac
          echo 'AC_CONFIG_FILES([Makefile])' >> configure.ac
          echo 'AC_OUTPUT' >> configure.ac
      - name: Ensure `configure.ac` is set up correctly
        run: |
          echo "AC_INIT([MyProject], [1.0], [your-email@example.com])" > configure.ac
          echo "AM_INIT_AUTOMAKE" >> configure.ac
          echo "AC_PROG_CC" >> configure.ac
          echo "AC_CONFIG_FILES([Makefile])" >> configure.ac
          echo "AC_OUTPUT" >> configure.ac

      - name: Create `Makefile.am`
        run: |
          echo "bin_PROGRAMS = my_program" > Makefile.am
          echo "my_program_SOURCES = main.c" >> Makefile.am

      - name: Regenerate configure script
        run: |
          autoreconf --install --force

      - name: Build APK
        run: |
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Terminal
          path: bin/*

      - name: Upload build logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: buildozer_logs
          path: .buildozer/android/build/*.log
