name: Build APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libssl-dev \
            libffi-dev \
            build-essential \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev
          sudo apt update
          pip install dbm gdbm nis tkinter
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.33
          export PATH=$PATH:~/.local/bin/
      - name: Install Python dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install cython buildozer
          sudo apt-get install --reinstall autoconf
      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses

      - name: Install Android SDK packages
        run: |
          sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"

      - name: Build APK
        run: |
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kivy-Test
          path: bin/*

      - name: Upload build logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: All_files
          path: .
