name: Build APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Android SDK Command-Line Tools
        run: |
          mkdir -p $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          sdkmanager --list
      
      - name: Install Required SDK Components
        run: |
          yes | sdkmanager --install "platforms;android-30" "build-tools;30.0.3" --sdk_root=$ANDROID_HOME
      
      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython
      
      - name: Build APK
        run: |
          yes | buildozer -v android debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: APK
          path: bin/*.apk
      
      - name: Upload Build Logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: Build Logs
          path: .buildozer/android/platform/*.log
