name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer build directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

      - name: Pull Buildozer Docker Image
        run: docker pull kivy/buildozer:latest

      - name: Build with Buildozer
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            kivy/buildozer:latest buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: .buildozer/android/platform/build/dists/**/build/outputs/apk/debug/*.apk
