name: Build APK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Install Android SDK and NDK
        run: |
          mkdir -p $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O ndk.zip
          unzip ndk.zip -d $HOME/android-sdk/ndk
          echo "ANDROID_NDK_HOME=$HOME/android-sdk/ndk/android-ndk-r25b" >> $GITHUB_ENV
          yes | sdkmanager --install "platforms;android-30" "build-tools;30.0.3" --sdk_root=$ANDROID_HOME
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install cython buildozer
      
      - name: Build APK
        run: |
          yes | buildozer -v android debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: APK
          path: bin/*.apk
      
      - name: Upload build logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: build_logs
          path: .buildozer/android/platform/*.log
