name: Build Android App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_android_app:
    runs-on: ubuntu-latest

    env:
      ANDROIDNDK: ${{ github.workspace }}/android-ndk-r25b
      BUILDOZER_WARN_ON_ROOT: 0
      BUILD_LOG_PATH: build_logs/build.log

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Create directories for logs and binaries
      - name: Create Directories
        run: |
          mkdir -p build_logs bin
          touch build_logs/build.log

      # Update and install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update | tee -a build_logs/build.log
          sudo apt-get install -y build-essential wget unzip python3 python3-pip openjdk-11-jdk git | tee -a build_logs/build.log
          sudo update-alternatives --config java <<< "2"

      # Setup Python environment
      - name: Setup Python Environment
        run: |
          python3 -m venv venv | tee -a build_logs/build.log
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel | tee -a build_logs/build.log
          pip install buildozer cython kivy | tee -a build_logs/build.log

      # Download and setup Android NDK
      - name: Download and Setup Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip | tee -a build_logs/build.log
          unzip android-ndk-r25b-linux.zip | tee -a build_logs/build.log
          export ANDROIDNDK=${{ github.workspace }}/android-ndk-r25b

      # Create Buildozer config
      - name: Configure Buildozer
        run: |
          mkdir -p ~/.buildozer
          echo "root = 1" >> ~/.buildozer/config.ini

      # Build APK
      - name: Build APK
        run: |
          set +e
          if buildozer android debug | tee -a build_logs/build.log; then
            echo "Build succeeded. Copying APK to bin/..."
            cp .buildozer/android/platform/build-arm64-v8a/dists/*/build/outputs/apk/debug/*.apk bin/ || true
          else
            echo "Build failed. Saving logs."
            mkdir -p build_logs_chunks
            split -b 3M build_logs/build.log build_logs_chunks/build_log_part_
          fi
          set -e

      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            bin/*.apk
            build_logs/*.log
            build_logs_chunks/*
          retention-days: 1
